@startuml

title Diagramme de classe du jeu de go

class GameController {
    + startGame()
    - playTurn()
    - allPlayerHavePassed()
}

class GameConsole {
    + promptAction(Player): Action
    + printBoard(string)
    + printResultError(ErrorType)
}

interface Deserializer {
    + deserialize(string)
}

class PositionDeserializer {
}

interface Action {
    + execute(Player, Board)
    + isAllowed(Player, Board)
}

class PassAction {}
class PlayAction {}

enum ErrorType {
    Ko
    Suicide
    InvalidPosition
    IntersectionTaken
}

class PlayerCarousel {
    - List<Player> players;
    + nextTurn()
    + getCurrentPlayer() : Player
}

class Player {
    - color: Color
    + hasPassed: boolean
    + pass()
    + resetPass()
}

enum Color{
    BLACK
    WHITE
}

class Board {
    - size: int
    - intersections: List<Intersection>
    + putStone(Position, Color)
    + getIntersection(Position): Intersection
    + getStoneGroup(Stone, List<Optional<Color>>)
    - removePrisoners(Intersection): void
}

class BoardController {
    - List<Board> boardHistory;
    - Board current;
    + addBoard(Board);
    + putStoneOnBoard
    + getSecondLastBoard(): Board;
    // Action validation
    + isPositionValid(Position)
    + isIntersectionVacant(Position)
    + isActionSuicide(Position, Player)
    + isActionKo(Position, Player)
}

class Intersection {
    - occupation: Color
    - position: Position
    + isVacant()
    + isEnemy()
    + isFriendly()
    + hasPosition(Position)
    + getNeighbors(Board)
    + getEnemyNeighbors(Board)
    + getFriendlyNeighbors(Board)
}

class Position {
    Position(x,y)
    - int x
    - int y
    + isValid(Board)
}

Action -.> Player
Action -.> BoardController
Action --> ErrorType

PassAction --> Action
PlayAction --> Action

Intersection --> Position

Board *--> Intersection
Board -.> BoardController

GameController -.> Action
GameController --> BoardController
GameController -> PlayerCarousel
GameController --> GameConsole

GameConsole --> Deserializer

PositionDeserializer -> Deserializer

Player --> Color

@enduml