@startuml

class Player{
- name: String
- prisoners: ArrayList<Stone>
- stones: ArrayList<Chain>
- nbPoint: int
+ playStone(t:Turn)
+ pass(t: Turn)
}
class Board{
- dimension: int
+ new(d: int, i: Intersection[])
}

class BoardController{
- logs: ArrayList<Turn>
+ createBoard()
+ deleteBoard()
+ calculateScore()
+ logTurn(t: Turn)
+ getLogs()

}

class Turn{
- action: Enum
}

class Chain{
- stones: ArrayList<Stone>
+ getLiberties()
+ atariState()
}



class Stone{
- color: Enum
- deadOrAlive: Enum
- liberties: int
- position: Intersection
- voisins: Intersection[]
}
class Intersection{
- occupation: bool
- line: Line
- column: Column
}

enum Line{}

enum Column{}

Board --* Intersection
Stone -- Intersection
Player -- Board
Chain --* Stone
Player --* Chain
BoardController -- Turn
BoardController --"2" Player
Player -- Turn
Intersection --"9" Line
Intersection --"9" Column


@enduml

